version: '3.7'
services:
  mongodb_container:
    image: mongo:3.6.3
    container_name: 'mongodb'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: